[package]
name = "aoc2021"
version = "0.1.0"
authors = ["Lauri Koskela <lapamiko@gmail.com>"]
edition = "2021"


[dependencies]
md5 = "0.7.0"
regex = "1.5.4"
lazy_static = "1.4.0"
itertools = "0.10.1"
num-integer = "0.1.44"
ndarray = "0.15.4"